// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQJ79DBfKwvbCjlzNYrCgTU5g5_Sg0WTM',
    appId: '1:582647822985:web:9c52566e9edda9d180e458',
    messagingSenderId: '582647822985',
    projectId: 'homeworkout-3c939',
    authDomain: 'homeworkout-3c939.firebaseapp.com',
    storageBucket: 'homeworkout-3c939.firebasestorage.app',
    measurementId: 'G-YEKLELSMWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIEpV415wXaZ2v5Lh75qZM4dKg9tZJDJk',
    appId: '1:582647822985:android:f49fa844ef2670bc80e458',
    messagingSenderId: '582647822985',
    projectId: 'homeworkout-3c939',
    storageBucket: 'homeworkout-3c939.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApEZ4qM4Eb8C6-ahiXDlwNanQfBwTWPUw',
    appId: '1:582647822985:ios:ce2851a31add54d080e458',
    messagingSenderId: '582647822985',
    projectId: 'homeworkout-3c939',
    storageBucket: 'homeworkout-3c939.firebasestorage.app',
    iosBundleId: 'com.example.homeWorkout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApEZ4qM4Eb8C6-ahiXDlwNanQfBwTWPUw',
    appId: '1:582647822985:ios:ce2851a31add54d080e458',
    messagingSenderId: '582647822985',
    projectId: 'homeworkout-3c939',
    storageBucket: 'homeworkout-3c939.firebasestorage.app',
    iosBundleId: 'com.example.homeWorkout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQJ79DBfKwvbCjlzNYrCgTU5g5_Sg0WTM',
    appId: '1:582647822985:web:f86aadf6f275686980e458',
    messagingSenderId: '582647822985',
    projectId: 'homeworkout-3c939',
    authDomain: 'homeworkout-3c939.firebaseapp.com',
    storageBucket: 'homeworkout-3c939.firebasestorage.app',
    measurementId: 'G-WHNPGVD3ZJ',
  );
}
